# Generated by Django 4.2.7 on 2025-07-08 05:16

import apps.tools.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.tools.models.tool_image_upload_path)),
                ('category', models.CharField(choices=[('Power Tools', 'Power Tools'), ('Hand Tools', 'Hand Tools'), ('Garden Tools', 'Garden Tools'), ('Cleaning', 'Cleaning'), ('Automotive', 'Automotive'), ('Measuring', 'Measuring'), ('Other', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool',
                'verbose_name_plural': 'Tools',
                'ordering': ['-created_at'],
            },
        ),
    ]
